import express from "express";
import mongoose from 'mongoose';
import productRouter from './routes/product';
import orderRouterr from './routes/order';
import { errors} from 'celebrate';
import path from 'path';
import { errorHandler } from "./middlewares/error-handler";
import { errorLogger, requestLogger } from "./middlewares/logger";
const cors = require('cors');
const app = express();
mongoose.connect('mongodb://127.0.0.1:27017/weblarek');
app.use(cors());
app.use(express.urlencoded({ extended: false }));
app.use(express.json());
app.use(requestLogger);
app.use('/', productRouter);
app.use('/', orderRouterr);
app.use(express.static(path.join(__dirname, 'public')));
app.use(errorLogger);
app.use(errorHandler);
app.use(errors());
app.listen(3000, () => {console.log('listening on port 3000')});